// Translation tables and the pure lookup logic over them.
//
// Deliberately a .js file with no React and no DOM access, for two reasons: the
// tests can import these functions directly (node cannot load .jsx), and the
// tables stay usable from any context. Everything that needs React lives in
// i18n.jsx, which re-exports from here.


export const LANGS = { en: 'English', zh: '中文' };

// Interpolate {name}-style placeholders. An undefined value leaves the placeholder
// in place, which makes a missing argument easy to spot.
export function interpolate(str, vars) {
  if (!vars) return str;
  return str.replace(/\{(\w+)\}/g, (m, k) => (vars[k] === undefined ? m : String(vars[k])));
}

// Look up a key: the requested language first, then English, then the key itself.
// Returning the key rather than a blank keeps an untranslated string visible.
export function translate(lang, key, vars) {
  const table = STRINGS[lang] || STRINGS.en;
  const raw = table[key] ?? STRINGS.en[key] ?? key;
  return interpolate(raw, vars);
}

// Game name: use the translation if the table has game.<id>, otherwise the
// displayName the server sent. If someone adds a game and forgets the entry, the
// lobby still shows the server's name rather than a raw key.
export function gameName(t, id, fallback) {
  const key = `game.${id}`;
  const out = t(key);
  return out === key ? (fallback || id) : out;
}

// Server error code -> text in the current language. The server only sends codes
// (see the note at the top of server/server.js).
// A code may carry one argument after a colon ("auth.passwordTooShort:8"), which
// fills the {n} placeholder, keeping limits that live in server config out of the
// translation tables.
// An unknown code is returned as-is: an older server still sending prose won't
// render as a blank, and a code added without a matching entry stays visible so
// the gap gets noticed.
export function serverError(t, code) {
  if (!code) return '';
  const [name, arg] = String(code).split(':');
  const key = `err.${name}`;
  const out = t(key, arg === undefined ? undefined : { n: arg });
  return out === key ? String(code) : out;
}

// ── String tables ────────────────────────────────────────
// Grouped by area of the UI; keys are <area>.<meaning>. The zh column keeps the
// original wording; the en column follows the usual English names for these games
// (狼人杀 = Werewolf/Mafia, 炸弹猫 = Exploding Kittens).
const STRINGS = {
  en: {
    // Common
    'app.title': 'Playground · Multiplayer Games',
    'common.you': ' (you)',
    'common.back': '← Back',
    'common.cancel': 'Cancel',
    'common.send': 'Send',
    'common.clear': 'Clear',
    'common.players': 'Players',
    'common.connecting': 'Connecting…',

    // Sign-in
    'auth.tagline': 'Real-time multiplayer game platform',
    'auth.login': 'Log in',
    'auth.register': 'Sign up',
    'auth.nickname': 'Nickname',
    'auth.namePlaceholder': 'Your name',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.pleaseWait': 'Please wait…',
    'auth.guestLabel': 'Or jump straight in as a guest',
    'auth.guestPlaceholder': 'Enter a nickname',
    'auth.playAsGuest': 'Play as guest',

    // Lobby
    'lobby.connected': '· Connected',
    'lobby.connecting': '· Connecting…',
    'lobby.logout': 'Log out',
    'lobby.chooseGame': 'Choose a game',
    'lobby.loadingGames': 'Loading… (check that the backend is running)',
    'lobby.playerRange': '{min}-{max} players · real-time',
    'lobby.createRoom': 'Create room',
    'lobby.joinByCode': 'Join with a room code',
    'lobby.join': 'Join',
    'lobby.calcTitle': 'Mahjong fan calculator (algorithm demo)',
    // Game names are translated by id. The server sends displayName per id; an id
    // missing here falls back to the server's name, so a new game without an entry
    // still shows something rather than a blank.
    'game.drawguess': 'Draw & Guess',
    'game.werewolf': 'Werewolf',
    'game.kittens': 'Exploding Kittens',

    // Room
    'room.scanToJoin': 'Scan the code, or join with room code',
    'room.playersCount': 'Players ({n}/{max})',
    'room.kick': 'Kick',
    'room.needPlayers': 'Needs at least {n} players',
    'room.start': 'Start game',
    'room.waitHost': 'Waiting for the host to start…',
    'room.kicked': 'The host removed you from the room',
    'room.spectating': '👀 Spectating (not playing this round)',
    'room.godView': ' · god view',
    'room.spectatorCount': '👀 {n} spectating{god}',
    'room.godViewSuffix': ' (roles visible)',
    'room.allowGodView': 'Let spectators see every role (god view)',
    'room.unknownGame': 'Unknown game type: {id}',
    'room.rematch': '🔄 Play again',
    'room.waitRematch': 'Waiting for the host to start another round…',
    'room.leave': '← Leave',
    'room.badge': 'Room {code}',

    // Game settings
    'settings.title': 'Game settings',
    'settings.hostOnly': ' (host can change)',
    'settings.wordLang': 'Word bank language',
    'settings.wordLangHint': 'Shared by the whole room, separate from your own interface language',
    'settings.wordLang.zh': 'Chinese',
    'settings.wordLang.en': 'English',
    'settings.roundsPerPlayer': 'Rounds per player',
    'settings.roundsUnit': '{n} rounds',
    'settings.drawTime': 'Drawing time per round',
    'settings.categories': 'Word categories',
    'settings.categoriesHint': '(none selected = all)',
    'settings.customWords': 'Custom word list',
    'settings.customWordsHint': '(one per line or comma-separated; if set, only these are used)',
    'settings.customPlaceholder': 'e.g. birthday cake, balloon, candle\n(leave empty to use the categories above)',
    'settings.customCount': '{n} custom words set',
    'settings.usingCategories': '(using category word list)',
    // The server's configSchema label/hint are translated by config key; a key that
    // is missing here falls back to the text the server sent (see schemaText in
    // LobbySettings).
    'cfg.tiePk': 'Tie goes to a runoff',
    'cfg.tiePk.hint': 'On a daytime tie, the tied players speak and everyone else votes again',
    'cfg.speechSeconds': 'Speech time per player',
    'cfg.speechSeconds.hint': 'Players speak in turn and can tap "Pass" to finish early',
    'cfg.daySeconds': 'Voting time',
    'cfg.daySeconds.hint': 'The voting phase after the speeches; votes can be changed',
    'cfg.nightSeconds': 'Night length',
    'cfg.nightSeconds.hint': 'Wolves pick a target and the seer checks someone',
    'cfg.witchSeconds': 'Witch time',
    'cfg.witchSeconds.hint': 'The witch appears at 7+ players',
    'cfg.hunterSeconds': 'Hunter time',
    'cfg.hunterSeconds.hint': 'The hunter appears at 10+ players',
    'cfg.pkSeconds': 'Runoff voting time',
    'cfg.pkSeconds.hint': 'Only used when runoffs are enabled',
    'cfg.revealSeconds': 'Role reveal time',
    'cfg.revealSeconds.hint': 'Starts early once everyone taps "Enter game"',
    'cfg.turnSeconds': 'Turn length',
    'cfg.turnSeconds.hint': 'On timeout a card is drawn for you',
    'cfg.nopeSeconds': 'Nope window',
    'cfg.nopeSeconds.hint': 'How long others get to nope an action card',
    'cfg.defuseSeconds': 'Bomb placement time',
    'cfg.defuseSeconds.hint': 'Time to choose where the bomb goes back in the deck',
    'cfg.favorSeconds': 'Favor time',
    'cfg.favorSeconds.hint': 'Time to pick a card to hand over; a random one is given at timeout',
    // Word categories: the value itself is Chinese (it is the server's word-bank key),
    // so only the display name is translated here.
    'cat.动物': 'Animals',
    'cat.食物': 'Food',
    'cat.物品': 'Objects',
    'cat.交通': 'Transport',
    'cat.自然': 'Nature',
    'cat.建筑': 'Buildings',

    // Draw & Guess
    'common.player': 'player',
    // Separator for lists of names: an ideographic comma in Chinese, a plain comma in
    // English - hardcoding '、' looks wrong in English text.
    'common.listSep': ', ',
    'draw.guessed': '✅ {name} guessed it! (+{points})',
    'draw.answerWas': 'The answer was: {word}',
    'draw.gameOver': '🏁 Game over!',
    'draw.finalRanking': '🏁 Final ranking',
    'draw.backToLobby': 'Back to lobby',
    'draw.round': 'Round {n}/{total}',
    'draw.pickWord': 'Pick a word to draw:',
    'draw.picking': '{name} is picking a word…',
    'draw.scoreboard': 'Scoreboard',
    'draw.guessPlaceholder': 'Type your guess…',
    'draw.guess': 'Guess',
    'draw.canvasClear': 'Clear',

    // Role reveal
    'reveal.shuffling': 'Shuffling…',
    'reveal.tapToFlip': '👆 Tap to reveal your role',
    'reveal.youAre': 'You are {emoji} {role}',
    'reveal.ready': '✓ Ready, waiting for the others…',
    'reveal.enterGame': 'Enter game',

    // Roles
    'role.wolf': 'Werewolf',
    'role.wolf.desc': 'Hunt one player each night with your pack',
    'role.seer': 'Seer',
    'role.seer.desc': 'Check one player\'s alignment each night',
    'role.witch': 'Witch',
    'role.witch.desc': 'One healing potion, one poison — one of each',
    'role.hunter': 'Hunter',
    'role.hunter.desc': 'On elimination, shoot one player (unless poisoned)',
    'role.villager': 'Villager',
    'role.villager.desc': 'Find the wolves by day and vote them out',

    // Werewolf
    'wolf.winWolf': '🐺 Werewolves win',
    'wolf.winVillage': '🏡 Village wins',
    'wolf.rolesRevealed': 'Roles revealed',
    'wolf.phase.night': '🌙 Night',
    'wolf.phase.speech': '🎤 Speeches',
    'wolf.phase.day': '☀️ Vote',
    'wolf.phase.pk': '⚔️ Runoff',
    'wolf.phase.witch': '🧪 Witch',
    'wolf.phase.hunter': '🔫 Hunter',
    'wolf.day': 'Day {n}',
    'wolf.spectator': '👀 Spectating{god}',
    'wolf.youAre': '{emoji} You are the {role}{dead}',
    'wolf.dead': ' · eliminated',
    'wolf.spectatingTitle': '👀 Spectating',
    'wolf.spectatingGod': 'You are not playing this round. The host enabled god view — all roles are visible on the right.',
    'wolf.spectatingNormal': 'You are not playing this round. You see public information only.',
    'wolf.teammates': '🐺 Pack: {names}',
    'wolf.loneWolf': '🐺 You are the only wolf',
    'wolf.seerLog': '🔮 Checks: {results}',
    'wolf.isWolf': 'wolf❌',
    'wolf.isGood': 'good✅',
    'wolf.potions': '🧪 Heal {heal} · Poison {poison}',
    'wolf.gunLoaded': '🔫 Gun loaded (fire on elimination, unless poisoned)',
    'wolf.gunUsed': '🔫 Gun already fired',
    'wolf.killed': '🔪 {names} went down',
    'wolf.peacefulNight': '🛡️ A peaceful night',
    'wolf.exiled': '🗳️ {name} was voted out',
    'wolf.shotTook': '🔫 {shooter} shot {target}',
    'wolf.noActionSpectator': '👀 Spectating — you cannot act',
    'wolf.deadWatching': 'You are out. Watch quietly…',
    'wolf.aliveCount': 'Players ({n} alive)',
    'wolf.victimsLastNight': '{names} were killed last night',
    'wolf.nobodyDied': 'A peaceful night — nobody died',
    'wolf.noOneDown': 'Nobody went down',
    'wolf.poisonTook': 'Poison took effect',

    // Speeches
    'speech.yourTurn': '🎤 Your turn to speak',
    'speech.othersTurn': '🎤 {name} is speaking',
    'speech.position': 'Speaker {n} of {total}',
    'speech.useChat': 'Speak in the chat box below, then tap "Pass"',
    'speech.pass': 'Pass (end my speech)',
    'speech.waiting': 'Someone else is speaking, please wait…',

    // Witch
    'witch.closeEyes': '🌙 Eyes closed — the witch is acting…',
    'witch.acted': '✓ Done, waiting for dawn…',
    'witch.pickPoison': '☠️ Choose who to poison',
    'witch.backFromPoison': 'Back',
    'witch.poisonPlayer': 'Poison {name}',
    'witch.tonightVictim': '🔪 {name} went down tonight',
    'witch.peaceful': '🌙 Peaceful night (nobody was attacked)',
    'witch.potionStatus': 'Heal {heal} · Poison {poison}',
    'witch.used': '❌ used',
    'witch.noSelfHeal': ' · no self-heal after night one',
    'witch.useHeal': '💊 Use the healing potion on {name}',
    'witch.usePoison': '☠️ Use the poison',
    'witch.skip': 'Skip (use nothing)',

    // Hunter
    'hunter.waiting': '{name} is the hunter and is choosing a target…',
    'hunter.confirm': '🔫 Confirm the shot?',
    'hunter.takeDown': 'Take down {name}',
    'hunter.confirmShoot': 'Confirm shot',
    'hunter.reselect': 'Choose again',
    'hunter.youAreOut': '🔫 You are out — take one player with you',
    'hunter.aim': 'Aim at {name}',
    'hunter.holdFire': 'Hold fire',

    // Night
    'night.wolfPick': '🐺 Choose tonight\'s target',
    'night.kill': 'Kill {name}',
    'night.wolfActed': '✓ Target locked, waiting for the others…',
    'night.seerDone': '🔮 Already checked tonight (once per night)',
    'night.seerPick': '🔮 Check a player\'s alignment',
    'night.check': 'Check {name}',
    'night.seerActed': '✓ Checked, waiting for the others…',
    'night.sleep': '🌙 Eyes closed, waiting for dawn…',

    // Voting
    'vote.instructions': 'Discuss and vote someone out · you can change your vote · settles faster once everyone has voted',
    'vote.tiePk': ' (a tie goes to a runoff)',
    'vote.tieNone': ' (a tie means nobody is out)',
    'vote.votePlayer': 'Vote {name}',
    'vote.abstain': 'Abstain',
    'vote.notVoted': 'You have not voted — no vote at the deadline counts as an abstention',
    'vote.allVoted': '✓ Everyone voted, settling shortly · you can still change',
    'pk.title': '⚔️ Runoff: {names}',
    'pk.iAmCandidate': 'You are in the runoff — defend yourself; the others decide',
    'pk.chooseOne': 'Pick one of the two · another tie means nobody is out',
    'pk.waitingVerdict': '⚔️ Waiting for the others to decide…',
    'pk.allVoted': '✓ Everyone voted, deciding shortly · you can still change',

    // Chat
    'chat.title': '💬 Discussion',
    'chat.deadChannel': ' · dead chat (living players cannot see this)',
    'chat.empty': 'Nobody has spoken yet…',
    'chat.deadPlaceholder': 'Talk to the dead…',
    'chat.placeholder': 'Say something…',
    'chat.spectator': 'Spectating — you can only read the discussion',
    'chat.nightMuted': '🌙 No public talking at night',
    'chat.waitTurn': '🎤 Speeches in progress, wait for your turn…',
    'chat.cannotSpeak': 'You cannot speak right now',

    // Exploding Kittens
    'kittens.card.bomb': 'Exploding Kitten',
    'kittens.card.defuse': 'Defuse',
    'kittens.card.nope': 'Nope',
    'kittens.card.attack': 'Attack',
    'kittens.card.skip': 'Skip',
    'kittens.card.favor': 'Favor',
    'kittens.card.shuffle': 'Shuffle',
    'kittens.card.future': 'See the Future',
    'kittens.card.cat_taco': 'Taco Cat',
    'kittens.card.cat_melon': 'Melon Cat',
    'kittens.card.cat_beard': 'Beard Cat',
    'kittens.card.cat_rainbow': 'Rainbow Cat',
    'kittens.card.cat_potato': 'Potato Cat',
    'kittens.card.cat_pair': 'Steal a card',
    'kittens.card.cat_three': 'Name a card',
    'kittens.card.cat_five': 'Take from discard',
    'kittens.winner': '🏆 {name} survived to the end',
    'kittens.ranking': 'Ranking',
    'kittens.deck': '🂠 Deck {n}',
    'kittens.nopeWindow': '🚫 Nope window',
    'kittens.defusing': '🙅 Defusing',
    'kittens.yourTurn': '🎯 Your turn',
    'kittens.theirTurn': '⏳ {name}\'s turn',
    'kittens.extraTurns': '⚔️ {n} more turns to play',
    'kittens.played': '{name} played {emoji} {card}',
    'kittens.wanted': ', asking for "{card}"',
    'kittens.nopedTimes': 'Noped {n}× — {effect}',
    'kittens.willNotResolve': 'will not take effect',
    'kittens.willResolve': 'will take effect',
    'kittens.resolvesAfter': 'Takes effect when the window closes',
    'kittens.nope': '🚫 Nope!',
    'kittens.favorAsked': '🤲 {name} asks you for a card',
    'kittens.favorPick': 'Tap a card below to hand it over · a random one is given at timeout',
    'kittens.favorWaiting': '🤲 {to} asked {from} for a card, waiting for them to choose…',
    'kittens.defusedBy': '🙅 {name} defused the bomb and is putting it back in the deck…',
    'kittens.futureTitle': '🔮 Top three cards (only you can see this)',
    'kittens.pickFromDiscard': '🐾 Pick a card from the discard pile',
    'kittens.discardEmpty': 'The discard pile is empty',
    'kittens.pickTarget': 'Choose a target player',
    'kittens.handCount': '{name} ({n} cards)',
    'kittens.nameACard': '🐾 Name a card to demand from {name}',
    'kittens.nameACardHint': 'They must hand it over if they have it, otherwise nothing (everyone sees the result)',
    'kittens.myHand': 'My hand ({n} cards)',
    'kittens.handGiveHint': ' · tap one to hand it over',
    'kittens.play': 'Play',
    'kittens.playCount': ' ({n} cards)',
    'kittens.drawEndTurn': 'Draw and end turn',
    'kittens.waitingFor': 'Waiting for {name}…',
    'kittens.youExploded': '💀 You got blown up. Watch quietly…',
    'kittens.spectatorNoHands': '👀 Spectating — nobody\'s hand is visible',
    'kittens.defuseSuccess': '🙅 Defused!',
    'kittens.defusePlace': 'Slide the bomb back into the deck — only you know where',
    'kittens.spotTop': 'Very top (the next player draws it immediately)',
    'kittens.spotSecond': '2nd from the top',
    'kittens.spotThird': '3rd from the top',
    'kittens.spotMiddle': 'Middle of the deck',
    'kittens.spotBottom': 'Very bottom (safest)',
    'kittens.blownUp': 'got blown up',

    // Fan calculator
    'calc.title': 'Fan Calculator',
    'calc.sub': 'FAN CALCULATOR · TENPAI CHECK',
    'calc.rule': 'RULE',
    'calc.ruleHK': '🇭🇰 Hong Kong',
    'calc.ruleGB': '🇨🇳 Chinese Official',
    'calc.inputMode': 'INPUT MODE',
    'calc.modePick': 'Tap to pick',
    'calc.modeText': 'Type it out',
    'calc.handEmptyPick': '13 tiles = tenpai check, 14 tiles = fan count',
    'calc.handEmptyText': 'Type a hand to preview it',
    'calc.tapToRemove': 'Tap to remove',
    'calc.textPlaceholder': '13 for tenpai / 14 for fan, e.g. 123m456p789s east east east red',
    'calc.formatLine': 'Format: number + suit (m chars, p dots, s bamboo, z honours)',
    'calc.honourLine': 'Honours: 1 East 2 South 3 West 4 North 5 Red 6 Green 7 White',
    'calc.example14': 'e.g. {hand} (14 tiles, fan count)',
    'calc.example13': 'e.g. {hand} (13 tiles, tenpai)',
    'calc.context': 'CONTEXT (applies to 14 tiles)',
    'calc.selfDraw': 'Self-draw',
    'calc.hasOpen': 'Has melds',
    'calc.calculating': 'Calculating…',
    'calc.checkTenpai': 'Check tenpai',
    'calc.countFan': 'Count fan',
    'calc.calcOrTenpai': 'Calculate / tenpai',
    'calc.tenpaiTitle': '🀄 Tenpai — one tile away',
    'calc.notTenpai': 'Not tenpai, keep drawing',
    'calc.won': 'Winning hand!',
    'calc.fanUnit': ' fan',
    'calc.needTiles': 'Need 13 or 14 tiles, you have {n}',
    'calc.noWin': 'Not a winning hand — check your tiles',
    'calc.belowMinimum': 'Winning shape, but below the 8-fan minimum (Chinese Official)',
    'calc.suit.m': 'Characters',
    'calc.suit.p': 'Dots',
    'calc.suit.s': 'Bamboo',
    'calc.suit.z': 'Honours',
    'calc.suffix.m': 'm',
    'calc.suffix.p': 'p',
    'calc.suffix.s': 's',
    'calc.wind.1': 'E',
    'calc.wind.2': 'S',
    'calc.wind.3': 'W',
    'calc.wind.4': 'N',
    'calc.dragon.5': 'R',
    'calc.dragon.6': 'G',
    'calc.dragon.7': 'Wh',
    'calc.err.badHonour': 'Invalid honour tile: z{n}',
    'calc.err.badTile': 'Invalid tile: {n}{suit}',
    'calc.err.unparsable': 'Could not parse the input',
    'calc.err.wrongCount': 'Need 13 or 14 tiles, you have {n}',

    // ── Server error codes ──
    // The server only sends codes (see the note atop server/server.js); the text lives
    // here. An unknown code is shown as-is by serverError(), so gaps are easy to spot.
    'err.client.connectFailed': 'Connection failed — check that the backend is running',
    'err.auth.missingFields': 'Enter your email and password',
    'err.auth.badParams': 'Invalid input',
    'err.auth.badEmail': 'That email address is not valid',
    'err.auth.passwordTooShort': 'Password must be at least {n} characters',
    'err.auth.passwordTooLong': 'Password is too long (max {n} bytes)',
    'err.auth.notLoggedIn': 'Not signed in',
    'err.auth.badToken': 'Invalid token',
    'err.auth.emailTaken': 'That email is already registered',
    'err.auth.badCredentials': 'Wrong email or password',
    'err.auth.needLoginOrGuest': 'Sign in or enter a guest name',
    'err.room.unknownGame': 'Unknown game',
    'err.room.notFound': 'Room not found',
    'err.room.full': 'The room is full',
    'err.room.notInRoom': 'You are not in a room',
    'err.room.hostOnlySettings': 'Only the host can change settings',
    'err.room.hostOnlyKick': 'Only the host can remove players',
    'err.room.hostOnlyRematch': 'Only the host can start another round',
    'err.room.hostOnlyStart': 'Only the host can start the game',
    'err.room.alreadyStarted': 'The game has already started',
    'err.room.notStarted': 'The game has not started',
    'err.room.noKickInGame': 'You cannot remove players mid-game',
    'err.room.noKickSelf': 'You cannot remove yourself',
    'err.room.notEnded': 'This round is not over yet',
    'err.room.spectatorCannotAct': 'You are spectating and cannot play this round',
    'err.room.needTwoPlayers': 'At least 2 players are needed',
    'err.game.unknownAction': 'Unknown action',
    'err.game.notAPlayer': 'You are not in this game',
    'err.game.badTarget': 'Invalid target',
    'err.game.notYourTurn': "It's not your turn",
    'err.game.youAreOut': 'You are out',
    'err.wolf.needFour': 'Werewolf needs at least 4 players',
    'err.wolf.notNight': 'Not the night phase',
    'err.wolf.notDayVote': 'Not the daytime voting phase',
    'err.wolf.notHunterPhase': 'Not the hunter phase',
    'err.wolf.notWitchPhase': 'Not the witch phase',
    'err.wolf.notSpeechPhase': 'Not the speech phase',
    'err.wolf.notPkPhase': 'Not the runoff phase',
    'err.wolf.onlyLiveWolf': 'Only a living wolf can act',
    'err.wolf.onlyLiveWitch': 'Only a living witch can use a potion',
    'err.wolf.onlySeer': 'Only the seer can check',
    'err.wolf.alreadyChecked': 'You already checked someone tonight',
    'err.wolf.alreadyActed': 'You already acted tonight',
    'err.wolf.noVictimTonight': 'Nobody was attacked tonight',
    'err.wolf.noCheckSelf': 'You cannot check yourself',
    'err.wolf.noPoisonSelf': 'You cannot poison yourself',
    'err.wolf.noSelfHeal': 'You cannot heal yourself',
    'err.wolf.onePotionPerNight': 'Only one potion per night',
    'err.wolf.healUsed': 'The healing potion is already used',
    'err.wolf.poisonUsed': 'The poison is already used',
    'err.wolf.notYourShot': 'It is not your shot',
    'err.wolf.notYourSpeech': 'It is not your turn to speak yet',
    'err.wolf.notSpeakingNow': 'It is not your turn to speak',
    'err.wolf.cannotSpeakPublic': 'You cannot speak publicly right now',
    'err.wolf.cannotSpeak': 'You cannot speak right now',
    'err.wolf.deadCannotVote': 'Eliminated players cannot vote',
    'err.wolf.pkCandidatesOnly': 'You can only vote for a runoff candidate',
    'err.wolf.pkCandidateCannotVote': 'Runoff candidates do not vote',
    'err.kittens.cannotPlay': 'You cannot play a card right now',
    'err.kittens.cannotDraw': 'You cannot draw right now',
    'err.kittens.noGiveNeeded': 'No card needs handing over right now',
    'err.kittens.noPlaceNeeded': 'No bomb needs placing right now',
    'err.kittens.nothingToNope': 'There is nothing to nope right now',
    'err.kittens.notYourGive': 'You are not the one handing over a card',
    'err.kittens.notYourDefuse': 'You are not the one defusing',
    'err.kittens.noNopeCard': 'You have no Nope card',
    'err.kittens.missingCard': 'You do not have that card',
    'err.kittens.missingCards': 'You do not have those cards',
    'err.kittens.noCardsSelected': 'No cards selected',
    'err.kittens.pickOneCard': 'Pick one card from your hand',
    'err.kittens.nameACard': 'Name the card you want',
    'err.kittens.pickFromDiscard': 'Pick a card from the discard pile',
    'err.kittens.notInDiscard': 'That card is not in the discard pile',
    'err.kittens.favorNeedsTarget': 'Favor needs a valid target',
    'err.kittens.needValidTarget': 'Choose a valid target player',
    'err.kittens.cannotPlayAlone': 'That card cannot be played on its own',
    'err.kittens.badCombo': 'You can only play: one action card / two or three matching cats / five different cats',
    'err.draw.onlyDrawerPicks': 'Only the drawer picks the word',
    'err.draw.onlyDrawerDraws': 'Only the drawer can draw',
    'err.draw.onlyDrawerClears': 'Only the drawer can clear the canvas',
    'err.draw.drawerCannotGuess': 'The drawer cannot guess',
    'err.draw.notPickPhase': 'Not the word-picking phase',
    'err.draw.cannotDraw': 'You cannot draw right now',
    'err.draw.cannotClear': 'You cannot clear right now',
    'err.draw.cannotGuess': 'You cannot guess right now',
    'err.draw.alreadyGuessed': 'You already guessed it',
    'err.draw.invalidWord': 'Invalid word',
    'err.draw.badStroke': 'Malformed stroke data',
  },

  zh: {
    'app.title': 'Playground · 多人游戏平台',
    'common.you': ' (你)',
    'common.back': '← 返回',
    'common.cancel': '取消',
    'common.send': '发送',
    'common.clear': '清空',
    'common.players': '玩家',
    'common.connecting': '连接中…',

    'auth.tagline': '多人实时游戏平台',
    'auth.login': '登录',
    'auth.register': '注册',
    'auth.nickname': '昵称',
    'auth.namePlaceholder': '你的名字',
    'auth.email': '邮箱',
    'auth.password': '密码',
    'auth.pleaseWait': '请稍候…',
    'auth.guestLabel': '或者直接以访客身份进入',
    'auth.guestPlaceholder': '输入昵称',
    'auth.playAsGuest': '以访客身份玩',

    'lobby.connected': '· 已连接',
    'lobby.connecting': '· 连接中…',
    'lobby.logout': '登出',
    'lobby.chooseGame': '选择游戏',
    'lobby.loadingGames': '加载中…(确认后端已启动)',
    'lobby.playerRange': '{min}-{max} 人 · 实时多人',
    'lobby.createRoom': '创建房间',
    'lobby.joinByCode': '用房间码加入',
    'lobby.join': '加入',
    'lobby.calcTitle': '麻将番型计算器 (算法工具)',
    'game.drawguess': '你画我猜',
    'game.werewolf': '狼人杀',
    'game.kittens': '炸弹猫',

    'room.scanToJoin': '扫码或用房间码',
    'room.playersCount': '玩家 ({n}/{max})',
    'room.kick': '踢出',
    'room.needPlayers': '至少需要 {n} 人',
    'room.start': '开始游戏',
    'room.waitHost': '等待房主开始…',
    'room.kicked': '你已被房主移出房间',
    'room.spectating': '👀 观战中(不参与本局)',
    'room.godView': ' · 上帝视角',
    'room.spectatorCount': '👀 {n} 人观战{god}',
    'room.godViewSuffix': '(可见身份)',
    'room.allowGodView': '允许观战者看到所有身份(上帝视角)',
    'room.unknownGame': '未知游戏类型:{id}',
    'room.rematch': '🔄 再来一局',
    'room.waitRematch': '等房主再来一局…',
    'room.leave': '← 离开',
    'room.badge': '房间 {code}',

    'settings.title': '游戏设置',
    'settings.hostOnly': '(房主可改)',
    'settings.wordLang': '词库语言',
    'settings.wordLangHint': '全房间共用,与你自己的界面语言无关',
    'settings.wordLang.zh': '中文',
    'settings.wordLang.en': 'English',
    'settings.roundsPerPlayer': '每人画几轮',
    'settings.roundsUnit': '{n} 轮',
    'settings.drawTime': '每轮作画时间',
    'settings.categories': '词库分类',
    'settings.categoriesHint': '(不选=全部)',
    'settings.customWords': '自定义词库',
    'settings.customWordsHint': '(每行/逗号一个词;填了则只用这些词)',
    'settings.customPlaceholder': '例:生日蛋糕, 气球, 蜡烛\n(留空则用上面的分类词库)',
    'settings.customCount': '已设 {n} 个自定义词',
    'settings.usingCategories': '(使用分类词库)',
    'cfg.tiePk': '平票进入 PK 加赛',
    'cfg.tiePk.hint': '白天平票时,平票者发言后其余玩家重投一轮',
    'cfg.speechSeconds': '每人发言时长',
    'cfg.speechSeconds.hint': '轮流发言,说完可点"过"提前结束',
    'cfg.daySeconds': '投票时长',
    'cfg.daySeconds.hint': '发言结束后的投票阶段,期间可改票',
    'cfg.nightSeconds': '夜晚时长',
    'cfg.nightSeconds.hint': '狼人选刀 + 预言家查验',
    'cfg.witchSeconds': '女巫用药时长',
    'cfg.witchSeconds.hint': '7 人及以上才有女巫',
    'cfg.hunterSeconds': '猎人开枪时长',
    'cfg.hunterSeconds.hint': '10 人及以上才有猎人',
    'cfg.pkSeconds': 'PK 投票时长',
    'cfg.pkSeconds.hint': '仅在开启平票 PK 时用到',
    'cfg.revealSeconds': '身份揭晓时长',
    'cfg.revealSeconds.hint': '所有人点"进入游戏"即提前开始',
    'cfg.turnSeconds': '单回合时长',
    'cfg.turnSeconds.hint': '超时会自动替你抽牌',
    'cfg.nopeSeconds': '否决响应窗口',
    'cfg.nopeSeconds.hint': '出功能牌后等待其他人否决的时间',
    'cfg.defuseSeconds': '拆弹放置时长',
    'cfg.defuseSeconds.hint': '选择炸弹塞回牌堆位置的时间',
    'cfg.favorSeconds': '索要给牌时长',
    'cfg.favorSeconds.hint': '被索要时挑一张牌给对方;超时随机给',
    'cat.动物': '动物',
    'cat.食物': '食物',
    'cat.物品': '物品',
    'cat.交通': '交通',
    'cat.自然': '自然',
    'cat.建筑': '建筑',

    'common.player': '玩家',
    'common.listSep': '、',
    'draw.guessed': '✅ {name} 猜中了! (+{points})',
    'draw.answerWas': '本轮答案是:{word}',
    'draw.gameOver': '🏁 游戏结束!',
    'draw.finalRanking': '🏁 最终排名',
    'draw.backToLobby': '返回大厅',
    'draw.round': '第 {n}/{total} 轮',
    'draw.pickWord': '选一个词来画:',
    'draw.picking': '{name} 正在选词…',
    'draw.scoreboard': '计分板',
    'draw.guessPlaceholder': '输入你的猜测…',
    'draw.guess': '猜',
    'draw.canvasClear': '清空',

    'reveal.shuffling': '洗牌中…',
    'reveal.tapToFlip': '👆 点击翻开你的身份',
    'reveal.youAre': '你是 {emoji} {role}',
    'reveal.ready': '✓ 已准备,等待其他玩家…',
    'reveal.enterGame': '进入游戏',

    'role.wolf': '狼人',
    'role.wolf.desc': '夜晚与同伴一起猎杀一名玩家',
    'role.seer': '预言家',
    'role.seer.desc': '每晚查验一名玩家的身份',
    'role.witch': '女巫',
    'role.witch.desc': '解药救人、毒药毒人,各一瓶',
    'role.hunter': '猎人',
    'role.hunter.desc': '出局时可开枪带走一名玩家(被毒除外)',
    'role.villager': '平民',
    'role.villager.desc': '白天找出并投票放逐狼人',

    'wolf.winWolf': '🐺 狼人阵营胜利',
    'wolf.winVillage': '🏡 好人阵营胜利',
    'wolf.rolesRevealed': '身份公开',
    'wolf.phase.night': '🌙 夜晚',
    'wolf.phase.speech': '🎤 轮流发言',
    'wolf.phase.day': '☀️ 投票放逐',
    'wolf.phase.pk': '⚔️ 平票 PK',
    'wolf.phase.witch': '🧪 女巫用药',
    'wolf.phase.hunter': '🔫 猎人开枪',
    'wolf.day': '第 {n} 天',
    'wolf.spectator': '👀 观战{god}',
    'wolf.youAre': '{emoji} 你是{role}{dead}',
    'wolf.dead': ' · 已出局',
    'wolf.spectatingTitle': '👀 观战中',
    'wolf.spectatingGod': '你不参与本局,房主已开启上帝视角,右侧可见所有身份',
    'wolf.spectatingNormal': '你不参与本局,仅可见公开信息',
    'wolf.teammates': '🐺 狼队友:{names}',
    'wolf.loneWolf': '🐺 你是唯一的狼',
    'wolf.seerLog': '🔮 查验记录:{results}',
    'wolf.isWolf': '狼人❌',
    'wolf.isGood': '好人✅',
    'wolf.potions': '🧪 解药 {heal} · 毒药 {poison}',
    'wolf.gunLoaded': '🔫 枪已上膛(出局时可开枪,被毒除外)',
    'wolf.gunUsed': '🔫 枪已用过',
    'wolf.killed': '🔪 {names} 倒牌了',
    'wolf.peacefulNight': '🛡️ 昨晚是平安夜',
    'wolf.exiled': '🗳️ {name} 被放逐了',
    'wolf.shotTook': '🔫 {shooter} 开枪带走了 {target}',
    'wolf.noActionSpectator': '👀 观战中,无法参与行动',
    'wolf.deadWatching': '你已出局,静静观战…',
    'wolf.aliveCount': '玩家 ({n} 存活)',
    'wolf.victimsLastNight': '昨晚 {names} 遇害了',
    'wolf.nobodyDied': '昨晚是平安夜,无人死亡',
    'wolf.noOneDown': '无人倒牌',
    'wolf.poisonTook': '毒药已生效',

    'speech.yourTurn': '🎤 轮到你发言了',
    'speech.othersTurn': '🎤 {name} 正在发言',
    'speech.position': '第 {n} / {total} 位',
    'speech.useChat': '在下方聊天框发言,说完点"过"',
    'speech.pass': '过(结束发言)',
    'speech.waiting': '其他人发言中,请等待…',

    'witch.closeEyes': '🌙 天黑请闭眼,女巫行动中…',
    'witch.acted': '✓ 已行动,等待天亮…',
    'witch.pickPoison': '☠️ 选择要毒的玩家',
    'witch.backFromPoison': '返回',
    'witch.poisonPlayer': '毒死 {name}',
    'witch.tonightVictim': '🔪 今晚 {name} 倒牌',
    'witch.peaceful': '🌙 今晚是平安夜(无人被刀)',
    'witch.potionStatus': '解药 {heal} · 毒药 {poison}',
    'witch.used': '❌ 已用',
    'witch.noSelfHeal': ' · 首夜之后不能自救',
    'witch.useHeal': '💊 使用解药救 {name}',
    'witch.usePoison': '☠️ 使用毒药',
    'witch.skip': '跳过(不用药)',

    'hunter.waiting': '{name} 是猎人,正在选择开枪目标…',
    'hunter.confirm': '🔫 确认开枪?',
    'hunter.takeDown': '带走 {name}',
    'hunter.confirmShoot': '确认开枪',
    'hunter.reselect': '重新选择',
    'hunter.youAreOut': '🔫 你出局了 —— 开枪带走一人',
    'hunter.aim': '瞄准 {name}',
    'hunter.holdFire': '放弃开枪',

    'night.wolfPick': '🐺 选择今晚猎杀的目标',
    'night.kill': '猎杀 {name}',
    'night.wolfActed': '✓ 已出刀,等待其他人行动…',
    'night.seerDone': '🔮 今晚已查验(每夜限一次)',
    'night.seerPick': '🔮 查验一名玩家的身份',
    'night.check': '查验 {name}',
    'night.seerActed': '✓ 已查验,等待其他人行动…',
    'night.sleep': '🌙 天黑请闭眼,等待天亮…',

    'vote.instructions': '讨论并投票放逐一名玩家 · 时间内可改票 · 全员投完后加速结算',
    'vote.tiePk': '(平票进入 PK 加赛)',
    'vote.tieNone': '(平票无人出局)',
    'vote.votePlayer': '投 {name}',
    'vote.abstain': '弃票',
    'vote.notVoted': '你还没投票 — 到点未投将视为弃票',
    'vote.allVoted': '✓ 全员已投,即将结算 · 仍可改票',
    'pk.title': '⚔️ 平票 PK:{names}',
    'pk.iAmCandidate': '你是 PK 候选人 —— 为自己辩护,由其余玩家裁决',
    'pk.chooseOne': '在候选人之间二选一 · 再次平票则无人出局',
    'pk.waitingVerdict': '⚔️ 等待其余玩家投票裁决…',
    'pk.allVoted': '✓ 全员已投,即将裁决 · 仍可改票',

    'chat.title': '💬 讨论',
    'chat.deadChannel': ' · 死人频道(存活玩家看不到)',
    'chat.empty': '还没有人发言…',
    'chat.deadPlaceholder': '对死者说…',
    'chat.placeholder': '发言讨论…',
    'chat.spectator': '观战中,仅可查看讨论',
    'chat.nightMuted': '🌙 夜晚不能公开发言',
    'chat.waitTurn': '🎤 轮流发言中,等待轮到你…',
    'chat.cannotSpeak': '当前不能发言',

    'kittens.card.bomb': '炸弹猫',
    'kittens.card.defuse': '拆弹',
    'kittens.card.nope': '否决',
    'kittens.card.attack': '攻击',
    'kittens.card.skip': '跳过',
    'kittens.card.favor': '索要',
    'kittens.card.shuffle': '洗牌',
    'kittens.card.future': '洞悉未来',
    'kittens.card.cat_taco': '塔可猫',
    'kittens.card.cat_melon': '西瓜猫',
    'kittens.card.cat_beard': '胡须猫',
    'kittens.card.cat_rainbow': '彩虹猫',
    'kittens.card.cat_potato': '土豆猫',
    'kittens.card.cat_pair': '偷牌',
    'kittens.card.cat_three': '指名要牌',
    'kittens.card.cat_five': '弃牌堆捡牌',
    'kittens.winner': '🏆 {name} 活到了最后',
    'kittens.ranking': '名次',
    'kittens.deck': '🂠 牌堆 {n}',
    'kittens.nopeWindow': '🚫 否决窗口',
    'kittens.defusing': '🙅 拆弹中',
    'kittens.yourTurn': '🎯 轮到你',
    'kittens.theirTurn': '⏳ {name} 的回合',
    'kittens.extraTurns': '⚔️ 还要打 {n} 回合',
    'kittens.played': '{name} 打出了 {emoji} {card}',
    'kittens.wanted': ',要「{card}」',
    'kittens.nopedTimes': '已被否决 {n} 次 —— {effect}',
    'kittens.willNotResolve': '当前不会生效',
    'kittens.willResolve': '当前会生效',
    'kittens.resolvesAfter': '窗口结束后生效',
    'kittens.nope': '🚫 否决!',
    'kittens.favorAsked': '🤲 {name} 向你索要一张牌',
    'kittens.favorPick': '点下方手牌选一张给他 · 超时会随机给',
    'kittens.favorWaiting': '🤲 {to} 向 {from} 索要一张牌,等他挑…',
    'kittens.defusedBy': '🙅 {name} 拆掉了炸弹,正在把它塞回牌堆…',
    'kittens.futureTitle': '🔮 牌堆顶三张(只有你看得到)',
    'kittens.pickFromDiscard': '🐾 从弃牌堆挑一张',
    'kittens.discardEmpty': '弃牌堆是空的',
    'kittens.pickTarget': '选择目标玩家',
    'kittens.handCount': '{name}({n} 张)',
    'kittens.nameACard': '🐾 向 {name} 指名要一张牌',
    'kittens.nameACardHint': '他有就必须给,没有则落空(所有人都会看到结果)',
    'kittens.myHand': '我的手牌({n} 张)',
    'kittens.handGiveHint': ' · 点一张给出去',
    'kittens.play': '出牌',
    'kittens.playCount': '({n} 张)',
    'kittens.drawEndTurn': '抽牌结束回合',
    'kittens.waitingFor': '等待 {name} 行动…',
    'kittens.youExploded': '💀 你被炸飞了,静静观战…',
    'kittens.spectatorNoHands': '👀 观战中,看不到任何人的手牌',
    'kittens.defuseSuccess': '🙅 拆弹成功!',
    'kittens.defusePlace': '把炸弹塞回牌堆 —— 只有你知道它在哪',
    'kittens.spotTop': '牌堆最顶(下一个人立刻抽到)',
    'kittens.spotSecond': '第 2 张',
    'kittens.spotThird': '第 3 张',
    'kittens.spotMiddle': '牌堆中间',
    'kittens.spotBottom': '牌堆最底(最安全)',
    'kittens.blownUp': '被炸飞了',

    'calc.title': '番型计算器',
    'calc.sub': 'FAN CALCULATOR · TENPAI CHECK',
    'calc.rule': '规则',
    'calc.ruleHK': '🇭🇰 香港',
    'calc.ruleGB': '🇨🇳 国标',
    'calc.inputMode': '输入方式',
    'calc.modePick': '点击选牌',
    'calc.modeText': '文字输入',
    'calc.handEmptyPick': '13张=听牌检查，14张=计算番数',
    'calc.handEmptyText': '输入牌型预览',
    'calc.tapToRemove': '点击移除',
    'calc.textPlaceholder': '13张听牌 / 14张算番，例：123m456p789s东东东中',
    'calc.formatLine': '格式：数字 + 花色（m万 p饼 s条 z字）',
    'calc.honourLine': '字牌：1东 2南 3西 4北 5中 6发 7白',
    'calc.example14': '例：{hand}（14张算番）',
    'calc.example13': '例：{hand}（13张听牌）',
    'calc.context': '情境（14张时有效）',
    'calc.selfDraw': '自摸',
    'calc.hasOpen': '有副露',
    'calc.calculating': '计算中...',
    'calc.checkTenpai': '检查听牌',
    'calc.countFan': '计算番数',
    'calc.calcOrTenpai': '计算 / 听牌',
    'calc.tenpaiTitle': '🀄 听牌 — 还差一张',
    'calc.notTenpai': '未听牌，继续摸牌',
    'calc.won': '和牌！',
    'calc.fanUnit': '番',
    'calc.needTiles': '需要 13 或 14 张牌，当前 {n} 张',
    'calc.noWin': '未和牌 — 请检查手牌',
    'calc.belowMinimum': '和牌但未达 8 番起和（国标规则）',
    'calc.suit.m': '万',
    'calc.suit.p': '饼',
    'calc.suit.s': '条',
    'calc.suit.z': '字',
    'calc.suffix.m': '万',
    'calc.suffix.p': '饼',
    'calc.suffix.s': '条',
    'calc.wind.1': '东',
    'calc.wind.2': '南',
    'calc.wind.3': '西',
    'calc.wind.4': '北',
    'calc.dragon.5': '中',
    'calc.dragon.6': '发',
    'calc.dragon.7': '白',
    'calc.err.badHonour': '无效字牌: z{n}',
    'calc.err.badTile': '无效数牌: {n}{suit}',
    'calc.err.unparsable': '无法解析输入',
    'calc.err.wrongCount': '需要13或14张牌，当前{n}张',

    // ── Server error codes ──
    // The server only sends codes (see the note atop server/server.js); the text lives
    // here. An unknown code is shown as-is by serverError(), so gaps are easy to spot.
    'err.client.connectFailed': '连接失败,请确认后端已启动',
    'err.auth.needLoginOrGuest': '需要登录或提供访客名',
    'err.auth.missingFields': '请填写邮箱和密码',
    'err.auth.badParams': '参数格式错误',
    'err.auth.badEmail': '邮箱格式不正确',
    'err.auth.passwordTooShort': '密码至少 {n} 个字符',
    'err.auth.passwordTooLong': '密码过长(最多 {n} 字节)',
    'err.auth.notLoggedIn': '未登录',
    'err.auth.badToken': 'Token 无效',
    'err.auth.emailTaken': '邮箱已注册',
    'err.auth.badCredentials': '邮箱或密码错误',
    'err.room.unknownGame': '未知游戏',
    'err.room.notFound': '房间不存在',
    'err.room.full': '房间已满',
    'err.room.notInRoom': '不在房间中',
    'err.room.hostOnlySettings': '只有房主能设置',
    'err.room.hostOnlyKick': '只有房主能踢人',
    'err.room.hostOnlyRematch': '只有房主能再来一局',
    'err.room.hostOnlyStart': '只有房主能开始',
    'err.room.alreadyStarted': '游戏已开始',
    'err.room.notStarted': '游戏未开始',
    'err.room.noKickInGame': '游戏进行中不能踢人',
    'err.room.noKickSelf': '不能踢自己',
    'err.room.notEnded': '本局尚未结束',
    'err.room.spectatorCannotAct': '观战中,无法参与对局',
    'err.room.needTwoPlayers': '至少需要 2 名玩家',
    'err.game.unknownAction': '未知动作',
    'err.game.notAPlayer': '你不是本局玩家',
    'err.game.badTarget': '目标无效',
    'err.game.notYourTurn': '还没轮到你',
    'err.game.youAreOut': '你已出局',
    'err.wolf.needFour': '狼人杀至少需要 4 人',
    'err.wolf.notNight': '非夜晚阶段',
    'err.wolf.notDayVote': '非白天投票阶段',
    'err.wolf.notHunterPhase': '非猎人开枪阶段',
    'err.wolf.notWitchPhase': '非女巫行动阶段',
    'err.wolf.notSpeechPhase': '非发言阶段',
    'err.wolf.notPkPhase': '非 PK 阶段',
    'err.wolf.onlyLiveWolf': '只有存活狼人能行动',
    'err.wolf.onlyLiveWitch': '只有存活女巫能用药',
    'err.wolf.onlySeer': '只有预言家能查验',
    'err.wolf.alreadyChecked': '今晚已经查验过了',
    'err.wolf.alreadyActed': '今晚已经行动过了',
    'err.wolf.noVictimTonight': '今晚没有人被刀',
    'err.wolf.noCheckSelf': '不能查验自己',
    'err.wolf.noPoisonSelf': '不能毒自己',
    'err.wolf.noSelfHeal': '不能自救',
    'err.wolf.onePotionPerNight': '同一夜只能用一瓶药',
    'err.wolf.healUsed': '解药已经用过了',
    'err.wolf.poisonUsed': '毒药已经用过了',
    'err.wolf.notYourShot': '不是你开枪',
    'err.wolf.notYourSpeech': '还没轮到你发言',
    'err.wolf.notSpeakingNow': '现在不是你发言',
    'err.wolf.cannotSpeakPublic': '现在还不能公开发言',
    'err.wolf.cannotSpeak': '当前不能发言',
    'err.wolf.deadCannotVote': '死亡玩家不能投票',
    'err.wolf.pkCandidatesOnly': '只能投 PK 候选人',
    'err.wolf.pkCandidateCannotVote': 'PK 候选人不参与投票',
    'err.kittens.cannotPlay': '现在不能出牌',
    'err.kittens.cannotDraw': '现在不能抽牌',
    'err.kittens.noGiveNeeded': '现在不用给牌',
    'err.kittens.noPlaceNeeded': '现在不用放置炸弹',
    'err.kittens.nothingToNope': '现在没有可否决的牌',
    'err.kittens.notYourGive': '不是你在给牌',
    'err.kittens.notYourDefuse': '不是你在拆弹',
    'err.kittens.noNopeCard': '你没有否决牌',
    'err.kittens.missingCard': '你没有这张牌',
    'err.kittens.missingCards': '你没有这些牌',
    'err.kittens.noCardsSelected': '没有选牌',
    'err.kittens.pickOneCard': '请选择一张手牌',
    'err.kittens.nameACard': '请指定要什么牌',
    'err.kittens.pickFromDiscard': '请从弃牌堆指定一张牌',
    'err.kittens.notInDiscard': '弃牌堆里没有这张牌',
    'err.kittens.favorNeedsTarget': '索要需要指定一名有效目标',
    'err.kittens.needValidTarget': '请选择一名有效的目标玩家',
    'err.kittens.cannotPlayAlone': '这张牌不能单独打出',
    'err.kittens.badCombo': '只能出:一张功能牌 / 两张或三张同款猫咪 / 五张不同猫咪',
    'err.draw.onlyDrawerPicks': '只有画手能选词',
    'err.draw.onlyDrawerDraws': '只有画手能画',
    'err.draw.onlyDrawerClears': '只有画手能清空',
    'err.draw.drawerCannotGuess': '画手不能猜',
    'err.draw.notPickPhase': '当前不是选词阶段',
    'err.draw.cannotDraw': '当前不能作画',
    'err.draw.cannotClear': '当前不能清空',
    'err.draw.cannotGuess': '当前不能猜词',
    'err.draw.alreadyGuessed': '你已经猜中了',
    'err.draw.invalidWord': '无效的词',
    'err.draw.badStroke': '笔画格式错误',
  },
};

// ── Yaku name translations ───────────────────────────────
// The scoring engine (calculator/rules/*) produces Chinese yaku names. Those names
// are themselves the lookup keys here, swapped for English names in the English UI.
// The benefit is that neither the engine nor its tests had to change: scoring logic
// stays completely decoupled from display language. The Chinese UI uses the engine's
// own output directly, so no second table is needed.
//
// English names follow the usual official translations (大四喜 = Big Four Winds, etc).
const YAKU_EN = {
  // Hong Kong yaku
  '国士无双': ['Thirteen Orphans', 'One of each terminal and honour plus a pair'],
  '七对': ['Seven Pairs', 'Seven pairs'],
  '豪华七对': ['Deluxe Seven Pairs', 'Seven pairs including four identical tiles'],
  '和牌': ['Winning hand', 'Basic winning hand'],
  '门清': ['Fully Concealed', 'No melds exposed'],
  '对对和': ['All Triplets', 'All sets are triplets (melds included)'],
  '幺九刻': ['Terminal Triplets', 'Triplets of 1s, 9s or honours'],
  '役牌：中': ['Value Tiles: Red Dragon', 'A set of dragon tiles'],
  '役牌：发': ['Value Tiles: Green Dragon', 'A set of dragon tiles'],
  '役牌：白': ['Value Tiles: White Dragon', 'A set of dragon tiles'],
  // Chinese Official yaku
  '十三幺': ['Thirteen Orphans', 'One of each terminal and honour plus any duplicate'],
  '连七对': ['Seven Consecutive Pairs', 'Seven consecutive pairs in one suit'],
  '门前清': ['Concealed Hand', 'No melds exposed'],
  '自摸': ['Self-draw', 'Won on your own draw'],
  '大四喜': ['Big Four Winds', 'Triplets of all four winds'],
  '大三元': ['Big Three Dragons', 'Triplets of red, green and white'],
  '绿一色': ['All Green', 'Made entirely of green tiles'],
  '九莲宝灯': ['Nine Gates', '1112345678999 in one suit plus any tile'],
  '小四喜': ['Little Four Winds', 'Three wind triplets plus a wind pair'],
  '小三元': ['Little Three Dragons', 'Two dragon triplets plus a dragon pair'],
  '字一色': ['All Honours', 'Every tile is an honour'],
  '四暗刻': ['Four Concealed Triplets', 'Four concealed triplets (concealed self-draw)'],
  '一色四同顺': ['Quadruple Chow', 'Four identical runs in one suit'],
  '一色四节高': ['Four Pure Shifted Triplets', 'Four triplets in one suit, each one higher'],
  '一色四步高': ['Four Pure Shifted Chows', 'Four shifted runs in one suit'],
  '混幺九': ['All Terminals and Honours', 'Every set and the pair holds terminals or honours'],
  '清一色': ['Full Flush', 'All one suit, no honours'],
  '一色三同顺': ['Pure Triple Chow', 'Three identical runs in one suit'],
  '一色三节高': ['Pure Shifted Triplets', 'Three triplets in one suit, each one higher'],
  '全大': ['Upper Tiles', 'Every tile is a 7, 8 or 9'],
  '全中': ['Middle Tiles', 'Every tile is a 4, 5 or 6'],
  '全小': ['Lower Tiles', 'Every tile is a 1, 2 or 3'],
  '清龙': ['Pure Straight', '1-9 in one suit as three runs'],
  '三色双龙会': ['Three-Suited Terminal Chows', 'Outside runs in three suits plus a pair'],
  '全带五': ['All Fives', 'Every set and the pair contains a 5'],
  '三同刻': ['Triple Triplet', 'The same number as a triplet in three suits'],
  '三暗刻': ['Three Concealed Triplets', 'Three concealed triplets'],
  '清幺九': ['All Terminals', 'Made entirely of 1s and 9s, no honours'],
  '碰碰和': ['All Triplets', 'Four triplets plus a pair'],
  '混一色': ['Half Flush', 'One suit plus honours'],
  '三风刻': ['Big Three Winds', 'Three wind triplets'],
  '大于五': ['All Above Five', 'Every tile is above 5'],
  '小于五': ['All Below Five', 'Every tile is below 5'],
  '断幺': ['All Simples', 'No terminals and no honours'],
  '全带幺': ['Outside Hand', 'Every set and the pair holds a terminal or honour'],
  '不求人': ['Fully Concealed Self-draw', 'Concealed hand won on a self-draw'],
  '平和': ['All Chows', 'Four runs plus a non-honour pair'],
  '圈风刻': ['Prevalent Wind', 'Triplet of the prevailing wind'],
  '门风刻': ['Seat Wind', 'Triplet of your own seat wind'],
};

// Translate the engine's { name, fan, description } into the same shape for the
// current language. Chinese is returned unchanged (the engine already emits Chinese);
// English is looked up, and a yaku with no translation yet falls back to the Chinese
// original so the UI still works instead of going blank.
// Names such as "幺九刻 x3" carry a count suffix: the base name is looked up and the
// suffix is appended back unchanged.
export function yakuText(lang, y) {
  if (lang !== 'en') return y;
  const hit = YAKU_EN[y.name];
  if (hit) return { ...y, name: hit[0], description: hit[1] };
  const [base, ...rest] = y.name.split(' ');
  const baseHit = YAKU_EN[base];
  if (!baseHit) return y;
  return { ...y, name: `${baseHit[0]} ${rest.join(' ')}`.trim(), description: baseHit[1] };
}
